package(default_visibility = ["//visibility:public"])

xcode_version(
    name = "version12_4_0_12D4e",
    aliases = [
        "12.4",
        "12.4.0",
        "12.4.0.12D4e",
    ],
    default_ios_sdk_version = "14.4",
    default_macos_sdk_version = "11.1",
    default_tvos_sdk_version = "14.3",
    default_watchos_sdk_version = "7.2",
    version = "12.4.0.12D4e",
)

xcode_config(
    name = "host_xcodes",
    default = ":version12_4_0_12D4e",
    versions = [
        ":version12_4_0_12D4e",
    ],
)
