name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare env
        run: |
          cat > ~/.netrc <<EOF
          machine api.github.com
          login ${{ secrets.SDKS_USER }}
          password ${{ secrets.SDKS_PASSWORD }}
          EOF
          chmod 600 ~/.netrc
          sed -i 's|SDKS_URL|${{ secrets.SDKS_URL }}|g' MODULE.bazel
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: >-
          bazel build --ios_multi_cpus=sim_arm64
          //examples/ios/HelloWorldSwiftUI:HelloWorld
          //examples/ios/HelloWorldSwiftUI:Tests
          //examples/ios/HelloWorldSwiftUI:UITests
          --remote_cache=${{ secrets.BAZEL_REMOTE_CACHE }}
          --google_default_credentials
          --remote_upload_local_results=true
      - run: cp -rL bazel-out/k8-fastbuild/bin/examples/ios/HelloWorldSwiftUI/Tests.runfiles . && tar -cJvf Tests.tar.xz Tests.runfiles && rm -rf Tests.runfiles
      - run: cp -rL bazel-out/k8-fastbuild/bin/examples/ios/HelloWorldSwiftUI/UITests.runfiles . && tar -cJvf UITests.tar.xz UITests.runfiles && rm -rf UITests.runfiles
      - uses: actions/upload-artifact@v4
        with:
          name: Tests
          path: Tests.tar.xz
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: UITests
          path: UITests.tar.xz
          retention-days: 1
  run_tests:
    needs: build
    runs-on: macOS-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Tests
      - run: |
          tar -xf Tests.tar.xz && cd Tests.runfiles/_main
          tmpdir=$(mktemp -d)
          exec env - PATH=/bin:/usr/bin \
            TEST_PREMATURE_EXIT_FILE="$tmpdir/premature_exit" \
            TEST_SRCDIR="$PWD" \
            TEST_UNDECLARED_OUTPUTS_DIR="$tmpdir/outputs" \
            XML_OUTPUT_FILE="$tmpdir/tests.xml" \
            examples/ios/HelloWorldSwiftUI/Tests
      - uses: actions/download-artifact@v4
        with:
          name: UITests
      - run: |
          tar -xf UITests.tar.xz && cd UITests.runfiles/_main
          tmpdir=$(mktemp -d)
          exec env - PATH=/bin:/usr/bin \
            TEST_PREMATURE_EXIT_FILE="$tmpdir/premature_exit" \
            TEST_SRCDIR="$PWD" \
            TEST_UNDECLARED_OUTPUTS_DIR="$tmpdir/outputs" \
            XML_OUTPUT_FILE="$tmpdir/uitests.xml" \
            examples/ios/HelloWorldSwiftUI/UITests
  # remote_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         echo "${{ secrets.BUILDBUDDY_ORG_CERT }}" > buildbuddy-cert.pem
  #         echo "${{ secrets.BUILDBUDDY_ORG_KEY }}" > buildbuddy-key.pem
  #     - run: bazel build --config=remote //examples/ios/HelloWorldSwiftUI:HelloWorld
